// 座席マスタ（物理的な座席配置）
export const seats = [
  // スクリーンNo.1 (110席) - 10行×11列を想定
  {
    id: 1,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 2,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 3,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 4,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 5,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 6,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 7,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 8,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 9,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 10,
    auditorium_id: 1,
    seat_row: "A",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 11,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 12,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 13,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 14,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 15,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 16,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 17,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 18,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 19,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 20,
    auditorium_id: 1,
    seat_row: "B",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 21,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 22,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 23,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 24,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 25,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 26,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 27,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 28,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 29,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 30,
    auditorium_id: 1,
    seat_row: "C",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 31,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 32,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 33,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 34,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 35,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 36,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 37,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 38,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 39,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 40,
    auditorium_id: 1,
    seat_row: "D",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 41,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 42,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 43,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 44,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 45,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 46,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 47,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 48,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 49,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 50,
    auditorium_id: 1,
    seat_row: "E",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 51,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 52,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 53,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 54,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 55,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 56,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 57,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 58,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 59,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 60,
    auditorium_id: 1,
    seat_row: "F",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 61,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 62,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 63,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 64,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 65,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 66,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 67,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 68,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 69,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 70,
    auditorium_id: 1,
    seat_row: "G",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 71,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 72,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 73,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 74,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 75,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 76,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 77,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 78,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 79,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 80,
    auditorium_id: 1,
    seat_row: "H",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 81,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 82,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 83,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 84,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 85,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 86,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 87,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 88,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 89,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 90,
    auditorium_id: 1,
    seat_row: "I",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 91,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 92,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 93,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 94,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 95,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 96,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 97,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 98,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 99,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 100,
    auditorium_id: 1,
    seat_row: "J",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 101,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 102,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 103,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 104,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 105,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 106,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 107,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 108,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 109,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 110,
    auditorium_id: 1,
    seat_row: "K",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  // スクリーンNo.2 (90席) - 9行×10列を想定
  {
    id: 1,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 2,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 3,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 4,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 5,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 6,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 7,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 8,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 9,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 10,
    auditorium_id: 2,
    seat_row: "A",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 11,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 12,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 13,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 14,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 15,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 16,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 17,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 18,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 19,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 20,
    auditorium_id: 2,
    seat_row: "B",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 21,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 22,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 23,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 24,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 25,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 26,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 27,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 28,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 29,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 30,
    auditorium_id: 2,
    seat_row: "C",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 31,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 32,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 33,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 34,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 35,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 36,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 37,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 38,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 39,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 40,
    auditorium_id: 2,
    seat_row: "D",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 41,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 42,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 43,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 44,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 45,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 46,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 47,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 48,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 49,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 50,
    auditorium_id: 2,
    seat_row: "E",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 51,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 52,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 53,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 54,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 55,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 56,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 57,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 58,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 59,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 60,
    auditorium_id: 2,
    seat_row: "F",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 61,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 62,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 63,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 64,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 65,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 66,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 67,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 68,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 69,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 70,
    auditorium_id: 2,
    seat_row: "G",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 71,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 72,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 73,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 74,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 75,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 76,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 77,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 78,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 79,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 80,
    auditorium_id: 2,
    seat_row: "H",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 81,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 82,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 83,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 84,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 85,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 86,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 87,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 88,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 89,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 90,
    auditorium_id: 2,
    seat_row: "I",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  // スクリーンNo.3 (100席) -  10行×10列を想定
  {
    id: 1,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 2,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 3,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 4,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 5,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 6,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 7,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 8,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 9,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 10,
    auditorium_id: 3,
    seat_row: "A",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 11,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 12,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 13,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 14,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 15,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 16,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 17,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 18,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 19,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 20,
    auditorium_id: 3,
    seat_row: "B",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 21,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 22,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 23,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 24,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 25,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 26,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 27,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 28,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 29,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 30,
    auditorium_id: 3,
    seat_row: "C",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 31,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 32,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 33,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 34,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 35,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 36,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 37,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 38,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 39,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 40,
    auditorium_id: 3,
    seat_row: "D",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 41,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 42,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 43,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 44,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 45,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 46,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 47,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 48,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 49,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 50,
    auditorium_id: 3,
    seat_row: "E",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 51,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 52,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 53,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 54,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 55,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 56,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 57,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 58,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 59,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 60,
    auditorium_id: 3,
    seat_row: "F",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 61,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 62,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 63,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 64,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 65,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 66,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 67,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 68,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 69,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 70,
    auditorium_id: 3,
    seat_row: "G",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 71,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 72,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 73,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 74,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 75,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 76,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 77,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: false,
    fee: 1800,
  },
  {
    id: 78,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 79,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 80,
    auditorium_id: 3,
    seat_row: "H",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 81,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 82,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 83,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 84,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 85,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 86,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 87,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 88,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 89,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 90,
    auditorium_id: 3,
    seat_row: "I",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 91,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "1",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 92,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "2",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 93,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "3",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 94,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "4",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 95,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "5",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 96,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "6",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 97,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "7",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 98,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "8",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 99,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "9",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
  {
    id: 100,
    auditorium_id: 3,
    seat_row: "J",
    seat_number: "10",
    seat_type: "STANDARD",
    is_available: true,
    fee: 1800,
  },
] as const;

// 座席予約状況（動的データ）
export const seat_reservations = [
  // schedule_id: 1 の予約例（いくつか予約済みにする）
  {
    id: 1,
    seat_id: 8,
    schedule_id: 1,
    reservation_id: 1001,
    status: "RESERVED" as const,
    locked_until: null,
  },
  {
    id: 2,
    seat_id: 9,
    schedule_id: 1,
    reservation_id: 1001,
    status: "RESERVED" as const,
    locked_until: null,
  },
  {
    id: 3,
    seat_id: 23,
    schedule_id: 1,
    reservation_id: 1002,
    status: "RESERVED" as const,
    locked_until: null,
  },
  {
    id: 4,
    seat_id: 24,
    schedule_id: 1,
    reservation_id: 1002,
    status: "RESERVED" as const,
    locked_until: null,
  },
  {
    id: 5,
    seat_id: 75,
    schedule_id: 1,
    reservation_id: null,
    status: "LOCKED" as const,
  }, // 仮予約中

  // schedule_id: 2 の予約例
  {
    id: 6,
    seat_id: 15,
    schedule_id: 2,
    reservation_id: 1003,
    status: "RESERVED" as const,
  },
  {
    id: 7,
    seat_id: 16,
    schedule_id: 2,
    reservation_id: 1003,
    status: "RESERVED" as const,
  },
  {
    id: 8,
    seat_id: 45,
    schedule_id: 2,
    reservation_id: null,
    status: "LOCKED" as const,
  }, // 仮予約中

  // schedule_id: 3 の予約例
  {
    id: 9,
    seat_id: 5,
    schedule_id: 3,
    reservation_id: 1004,
    status: "RESERVED" as const,
  },
  {
    id: 10,
    seat_id: 6,
    schedule_id: 3,
    reservation_id: 1004,
    status: "RESERVED" as const,
  },
];
