// lib/theaterResponseData.ts

export const prefectures = [
  { id: 1, name: "北海道" },
  { id: 2, name: "青森県" },
  { id: 3, name: "岩手県" },
  { id: 4, name: "宮城県" },
  { id: 5, name: "秋田県" },
  { id: 6, name: "山形県" },
  { id: 7, name: "福島県" },
  { id: 8, name: "茨城県" },
  { id: 9, name: "栃木県" },
  { id: 10, name: "群馬県" },
  { id: 11, name: "埼玉県" },
  { id: 12, name: "千葉県" },
  { id: 13, name: "東京都" },
  { id: 14, name: "神奈川県" },
  { id: 15, name: "新潟県" },
  { id: 16, name: "富山県" },
  { id: 17, name: "石川県" },
  { id: 18, name: "福井県" },
  { id: 19, name: "山梨県" },
  { id: 20, name: "長野県" },
  { id: 21, name: "岐阜県" },
  { id: 22, name: "静岡県" },
  { id: 23, name: "愛知県" },
  { id: 24, name: "三重県" },
  { id: 25, name: "滋賀県" },
  { id: 26, name: "京都府" },
  { id: 27, name: "大阪府" },
  { id: 28, name: "兵庫県" },
  { id: 29, name: "奈良県" },
  { id: 30, name: "和歌山県" },
  { id: 31, name: "鳥取県" },
  { id: 32, name: "島根県" },
  { id: 33, name: "岡山県" },
  { id: 34, name: "広島県" },
  { id: 35, name: "山口県" },
  { id: 36, name: "徳島県" },
  { id: 37, name: "香川県" },
  { id: 38, name: "愛媛県" },
  { id: 39, name: "高知県" },
  { id: 40, name: "福岡県" },
  { id: 41, name: "佐賀県" },
  { id: 42, name: "長崎県" },
  { id: 43, name: "熊本県" },
  { id: 44, name: "大分県" },
  { id: 45, name: "宮崎県" },
  { id: 46, name: "鹿児島県" },
  { id: 47, name: "沖縄県" },
];

export const cities = [
  { id: 1, name: "港区", alias: "minato-ku" },
  { id: 2, name: "新宿区", alias: "shinjuku-ku" },
  { id: 3, name: "大阪市", alias: "osaka-shi" },
  { id: 4, name: "福井市", alias: "fukui-shi" },
  { id: 5, name: "福岡市", alias: "fukuoka-shi" },
  { id: 6, name: "札幌市", alias: "sapporo-shi" },
  { id: 7, name: "青森市", alias: "aomori-shi" },
  { id: 8, name: "盛岡市", alias: "morioka-shi" },
  { id: 9, name: "仙台市", alias: "sendai-shi" },
  { id: 10, name: "秋田市", alias: "akita-shi" },
  { id: 11, name: "山形市", alias: "yamagata-shi" },
  { id: 12, name: "郡山市", alias: "koriyama-shi" },
  { id: 13, name: "水戸市", alias: "mito-shi" },
  { id: 14, name: "宇都宮市", alias: "utsunomiya-shi" },
  { id: 15, name: "前橋市", alias: "maebashi-shi" },
  { id: 16, name: "さいたま市", alias: "saitama-shi" },
  { id: 17, name: "千葉市", alias: "chiba-shi" },
  { id: 18, name: "横浜市", alias: "yokohama-shi" },
  { id: 19, name: "新潟市", alias: "niigata-shi" },
  { id: 20, name: "富山市", alias: "toyama-shi" },
  { id: 21, name: "金沢市", alias: "kanazawa-shi" },
  { id: 22, name: "甲府市", alias: "kofu-shi" },
  { id: 23, name: "長野市", alias: "nagano-shi" },
  { id: 24, name: "岐阜市", alias: "gifu-shi" },
  { id: 25, name: "静岡市", alias: "shizuoka-shi" },
  { id: 26, name: "名古屋市", alias: "nagoya-shi" },
  { id: 27, name: "津市", alias: "tsu-shi" },
  { id: 28, name: "大津市", alias: "otsu-shi" },
  { id: 29, name: "京都市", alias: "kyoto-shi" },
  { id: 30, name: "神戸市", alias: "kobe-shi" },
];

export const theaters = [
  { id: 1, name: "新宿シネマ", prefecture_id: 13, city_id: 2 },
  { id: 2, name: "お台場シアター", prefecture_id: 1, city_id: 1 },
  { id: 3, name: "梅田シネプレックス", prefecture_id: 2, city_id: 3 },
  { id: 4, name: "TOHO CINEMAS 福井", prefecture_id: 3, city_id: 4 },
  {
    id: 5,
    name: "ユナイテッドシネマ 福岡ももち",
    prefecture_id: 4,
    city_id: 5,
  },
  { id: 6, name: "札幌ムービーパーク", prefecture_id: 1, city_id: 6 },
  { id: 7, name: "青森シネマタウン", prefecture_id: 2, city_id: 7 },
  { id: 8, name: "盛岡フィルムホール", prefecture_id: 3, city_id: 8 },
  { id: 9, name: "仙台スクリーンプレイス", prefecture_id: 4, city_id: 9 },
  { id: 10, name: "秋田シネマガーデン", prefecture_id: 5, city_id: 10 },
  { id: 11, name: "山形シネマクラブ", prefecture_id: 6, city_id: 11 },
  { id: 12, name: "郡山シネマシティ", prefecture_id: 7, city_id: 12 },
  { id: 13, name: "水戸シネマスタジオ", prefecture_id: 8, city_id: 13 },
  { id: 14, name: "宇都宮シネマワールド", prefecture_id: 9, city_id: 14 },
  { id: 15, name: "前橋シネマドーム", prefecture_id: 10, city_id: 15 },
  { id: 16, name: "さいたまシネマスクエア", prefecture_id: 11, city_id: 16 },
  { id: 17, name: "千葉ムービーセンター", prefecture_id: 12, city_id: 17 },
  { id: 18, name: "横浜シネマプレイス", prefecture_id: 14, city_id: 18 },
  { id: 19, name: "新潟シネマステーション", prefecture_id: 15, city_id: 19 },
  { id: 20, name: "富山シネマライズ", prefecture_id: 16, city_id: 20 },
  { id: 21, name: "金沢シネマリンク", prefecture_id: 17, city_id: 21 },
  { id: 22, name: "甲府シネマハウス", prefecture_id: 19, city_id: 22 },
  { id: 23, name: "長野シネマフォーラム", prefecture_id: 20, city_id: 23 },
  { id: 24, name: "岐阜シネマロード", prefecture_id: 21, city_id: 24 },
  { id: 25, name: "静岡シネマパレス", prefecture_id: 22, city_id: 25 },
  { id: 26, name: "新宿ムービーハウス", prefecture_id: 13, city_id: 2 },
];

export const theater_details = [
  {
    id: 1,
    theater_id: 1,
    post_code: "160-0022",
    address: "東京都新宿区新宿5-12-4",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 2,
    theater_id: 2,
    post_code: "135-0064",
    address: "東京都江東区青海1-1-10",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 3,
    theater_id: 3,
    post_code: "530-0017",
    address: "大阪府大阪市北区角田町7-10",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 4,
    theater_id: 4,
    post_code: "910-0836",
    address: "福井県福井市大和田2丁目1201",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 5,
    theater_id: 5,
    post_code: "810-0065",
    address: "福岡県福岡市地行浜２丁目２−１",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 6,
    theater_id: 6,
    post_code: "060-0005",
    address: "北海道札幌市中央区北5条西2丁目",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 7,
    theater_id: 7,
    post_code: "030-0801",
    address: "青森県青森市新町1丁目13-2",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 8,
    theater_id: 8,
    post_code: "020-0022",
    address: "岩手県盛岡市大通2丁目8-14",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 9,
    theater_id: 9,
    post_code: "980-0811",
    address: "宮城県仙台市青葉区一番町4丁目9-18",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 10,
    theater_id: 10,
    post_code: "010-0001",
    address: "秋田県秋田市中通2丁目3-8",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 11,
    theater_id: 11,
    post_code: "990-0039",
    address: "山形県山形市香澄町2丁目8-1",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 12,
    theater_id: 12,
    post_code: "963-8002",
    address: "福島県郡山市駅前2丁目11-1",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 13,
    theater_id: 13,
    post_code: "310-0015",
    address: "茨城県水戸市宮町1丁目7-44",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 14,
    theater_id: 14,
    post_code: "320-0802",
    address: "栃木県宇都宮市江野町7-1",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 15,
    theater_id: 15,
    post_code: "371-0022",
    address: "群馬県前橋市千代田町2丁目5-1",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 16,
    theater_id: 16,
    post_code: "330-0854",
    address: "埼玉県さいたま市大宮区桜木町1丁目6-2",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 17,
    theater_id: 17,
    post_code: "260-0015",
    address: "千葉県千葉市中央区富士見2丁目5-1",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 18,
    theater_id: 18,
    post_code: "220-0005",
    address: "神奈川県横浜市西区南幸2丁目16-1",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 19,
    theater_id: 19,
    post_code: "950-0088",
    address: "新潟県新潟市中央区万代1丁目3-1",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 20,
    theater_id: 20,
    post_code: "930-0002",
    address: "富山県富山市新富町1丁目2-3",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 21,
    theater_id: 21,
    post_code: "920-0981",
    address: "石川県金沢市片町2丁目2-15",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 22,
    theater_id: 22,
    post_code: "400-0031",
    address: "山梨県甲府市丸の内1丁目16-20",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 23,
    theater_id: 23,
    post_code: "380-0823",
    address: "長野県長野市南千歳1丁目17-4",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 24,
    theater_id: 24,
    post_code: "500-8833",
    address: "岐阜県岐阜市神田町9丁目1",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 25,
    theater_id: 25,
    post_code: "420-0852",
    address: "静岡県静岡市葵区紺屋町6-7",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 26,
    theater_id: 26,
    post_code: "460-0008",
    address: "東京都新宿区北新宿11-5",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 27,
    theater_id: 27,
    post_code: "514-0004",
    address: "三重県津市栄町3丁目232",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 28,
    theater_id: 28,
    post_code: "520-0043",
    address: "滋賀県大津市中央1丁目8-13",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 29,
    theater_id: 29,
    post_code: "604-8031",
    address: "京都府京都市中京区河原町通三条下る",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 30,
    theater_id: 30,
    post_code: "650-0012",
    address: "兵庫県神戸市中央区北長狭通2丁目1-1",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 31,
    theater_id: 6,
    post_code: "060-0005",
    address: "北海道札幌市中央区北5条西2丁目",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 32,
    theater_id: 7,
    post_code: "030-0801",
    address: "青森県青森市新町1丁目13-2",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 33,
    theater_id: 8,
    post_code: "020-0022",
    address: "岩手県盛岡市大通2丁目8-14",
    photo_path: "/theater/test-screen3.png",
  },
  {
    id: 34,
    theater_id: 9,
    post_code: "980-0811",
    address: "宮城県仙台市青葉区一番町4丁目9-18",
    photo_path: "/theater/test-screen1.png",
  },
  {
    id: 35,
    theater_id: 10,
    post_code: "010-0001",
    address: "秋田県秋田市中通2丁目3-8",
    photo_path: "/theater/test-screen2.png",
  },
  {
    id: 36,
    theater_id: 36,
    post_code: "160-0021",
    address: "東京都新宿区歌舞伎町1丁目2-3",
    photo_path: "/theater/test-screen3.png",
  },
];
